version: "3"
services:
  english_app:
    container_name: english_app
    tty: true
    build: .
    volumes:
      - .:/home/sample_user
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=${LOCAL_IP_ADDR}
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
