export const ENGLISH_DATA  = [
  { id: '0', ja: '何を考えてるの？', en: 'what are you thinking', img: '01' },
  { id: '1', ja: 'お腹が空いてます', en: "I'm hungry", img: '03' },
  { id: '2', ja: '今何しているの', en: 'what are you doing', img: '05' },
  { id: '3', ja: '幸せです', en: "I'm happy", img: '04' },
  { id: '4', ja: '私は学生です', en: 'I am a student', img: '02' },
  { id: '5', ja: '彼女は背が高いです', en: 'She is tall', img: '06' },
  { id: '6', ja: '彼らは幸せです', en: 'They are happy', img: '07' },
  { id: '7', ja: '彼は私の兄です', en: 'He is my brother', img: '06' },
  { id: '8', ja: 'あなたは私の友達です', en: 'You are my friend', img: '09' },
  { id: '9', ja: '私たちはお腹が空いています', en: 'We are hungry', img: '10' },
  { id: '10', ja: '外は雨です', en: 'It is raining outside', img: '11' },
  { id: '11', ja: 'その花は美しいです', en: 'The flowers are beautiful', img: '12' },
  { id: '12', ja: '私は疲れています', en: 'I am tired', img: '13' },
  { id: '13', ja: '彼女は頭がいいです', en: 'She is smart', img: '14' },
  { id: '14', ja: '彼らは忙しいです', en: 'They are busy', img: '15' },
  { id: '15', ja: '彼は優しいです', en: 'He is kind', img: '16' },
  { id: '16', ja: 'あなたはおもしろいです', en: 'You are funny', img: '17' },
  { id: '17', ja: '私たちは遅れています', en: 'We are late', img: '18' },
  { id: '18', ja: '外は寒いです', en: 'It is cold outside', img: '19' },
  { id: '19', ja: 'その食べ物はおいしいです', en: 'The food is delicious', img: '20' },
  { id: '20', ja: '私は幸せです', en: 'I am happy', img: '21' },
  { id: '21', ja: '彼女は美しいです', en: 'She is beautiful', img: '22' },
  { id: '22', ja: '彼らはフレンドリーです', en: 'They are friendly', img: '23' },
  { id: '24', ja: '彼はおもしろいです', en: 'He is funny', img: '24' },
  { id: '25', ja: 'あなたは優しいです', en: 'You are kind', img: '25' },
  { id: '26', ja: '私たちは興奮しています', en: 'We are excited', img: '26' },
  { id: '27', ja: '外は暑いです', en: 'It is hot outside', img: '27' },
  { id: '28', ja: 'その映画は面白いです', en: 'The movie is interesting', img: '28' },
  { id: '29', ja: '私は悲しいです', en: 'I am sad', img: '29' },
  { id: '30', ja: '彼女は成功しています', en: 'She is successful', img: '30' },
  { id: '31', ja: '彼らは才能があります', en: 'They are talented', img: '31' },
  { id: '32', ja: '彼は強いです', en: 'He is strong', img: '32' },
  { id: '33', ja: 'あなたは役に立ちます', en: 'You are helpful', img: '33' },
  { id: '34', ja: '私たちは準備ができています', en: 'We are ready', img: '34' },
  { id: '35', ja: '外は暗いです', en: 'It is dark outside', img: '35' },
  { id: '36', ja: 'その音楽はうるさいです', en: 'The music is loud', img: '36' },
  { id: '37', ja: '私は恋をしています', en: 'I am in love', img: '37' },
  { id: '38', ja: '彼女はクリエイティブです', en: 'She is creative', img: '38' },
  { id: '39', ja: '彼らは寛大です', en: 'They are generous', img: '40' },
  { id: '40', ja: '私は幸せです', en: 'I am happy', img: '39' },
  { id: '41', ja: 'あなたは遅れています', en: 'You are late', img: '41' },
  { id: '42', ja: '彼は背が高いです', en: 'He is tall', img: '42' },
  { id: '43', ja: '彼女は美しいです', en: 'She is beautiful', img: '43' },
  { id: '44', ja: '私はあまり気分が良くありません', en: "I'm not feeling very well", img: '278' },
  { id: '45', ja: '私たちは疲れています', en: 'We are tired', img: '44' },
  { id: '46', ja: '彼らは頭が良いです', en: 'They are smart', img: '45' },
  { id: '47', ja: '空は青いです', en: 'The sky is blue', img: '46' },
  { id: '48', ja: '花は咲いています', en: 'The flowers are blooming', img: '47' },
  { id: '49', ja: '水は熱いです', en: 'The water is hot', img: '48' },
  { id: '50', ja: '食べ物はおいしいです', en: 'The food is delicious', img: '49' },
  { id: '51', ja: '空気はきれいです', en: 'The air is clean', img: '50' },
  { id: '52', ja: 'その映画は退屈です', en: 'The movie is boring', img: '51' },
  { id: '53', ja: 'その本は興味深いです', en: 'The book is interesting', img: '52' },
  { id: '54', ja: '家は大きいです', en: 'The house is big', img: '53' },
  { id: '55', ja: '車は速いです', en: 'The car is fast', img: '54' },
  { id: '56', ja: '犬は可愛いです', en: 'The dog is cute', img: '55' },
  { id: '57', ja: '猫は寝ています', en: 'The cat is sleeping', img: '56' },
  { id: '58', ja: '太陽は輝いています', en: 'The sun is shining', img: '57' },
  { id: '59', ja: '星はきらめいています', en: 'The stars are twinkling', img: '58' },
  { id: '60', ja: '空は曇っています', en: 'The sky is cloudy', img: '59' },
  { id: '61', ja: '草は緑です', en: 'The grass is green', img: '60' },
  { id: '62', ja: '木は高いです', en: 'The tree is tall', img: '61' },
  { id: '63', ja: '海は深いです', en: 'The ocean is deep', img: '62' },
  { id: '64', ja: '山々は壮大です', en: 'The mountains are majestic', img: '63' },
  { id: '65', ja: '町は混雑しています', en: 'The city is crowded', img: '64' },
  { id: '66', ja: '今日は疲れている気がします', en: "I'm feeling tired today", img: '65' },
  { id: '67', ja: '今夜のコンサートが楽しみです', en: "I'm excited for the concert tonight", img: '66' },
  { id: '68', ja: 'パーティーに参加できなくてごめんなさい', en: "I'm sorry I can't make it to the party", img: '67' },
  { id: '69', ja: 'スポーツ観戦には興味がありません', en: "I'm not interested in watching sports", img: '68' },
  { id: '70', ja: '明日の会議に参加できるかどうかわかりません', en: "I'm not sure if I can come to the meeting tomorrow", img: '69' },
  { id: '71', ja: '辛い食べ物は好きではありません', en: "I'm not a fan of spicy food", img: '70' },
  { id: '72', ja: 'この本はとても楽しんでいます', en: "I'm really enjoying this book", img: '71' },
  { id: '73', ja: 'まだ決断する準備ができていません', en: "I'm not ready to make a decision yet", img: '72' },
  { id: '74', ja: '遅れてごめんなさい', en: "I'm sorry for being late", img: '73' },
  { id: '75', ja: '月は満月です', en: 'The moon is full', img: '74' },
  { id: '76', ja: '新しい仕事に満足しています', en: "I'm happy with my new job", img: '75' },
  { id: '77', ja: '今日は調子が悪いです', en: "I'm not feeling well today", img: '76' },
  { id: '78', ja: '週末が楽しみです', en: "I'm looking forward to the weekend", img: '77' },
  { id: '79', ja: 'プレゼンテーションは苦手です', en: "I'm not good at public speaking", img: '78' },
  { id: '80', ja: '新しい言語を学ぶことに興味があります', en: "I'm interested in learning a new language", img: '79' },
  { id: '81', ja: 'ここでの寒さに慣れていません', en: "I'm not used to the cold weather here", img: '80' },
  { id: '82', ja: 'あなたの仕事には本当に感心しました', en: "I'm really impressed by your work", img: '81' },
  { id: '83', ja: 'ホラー映画はあまり好きではありません', en: "I'm not a big fan of horror movies", img: '51' },
  { id: '84', ja: 'すしは好きですか？', en: 'Do you like sushi?', img: '83' },
  { id: '85', ja: 'それを手伝いましょうか？', en: 'Do you need any help with that?', img: '84' },
  { id: '86', ja: '週末の予定はありますか？', en: 'Do you have any plans for the weekend?', img: '85' },
  { id: '87', ja: 'この質問の答えを知っていますか？', en: 'Do you know the answer to this question?', img: '86' },
  { id: '88', ja: '今夜、外食に行きたいですか？', en: 'Do you want to go out for dinner tonight?', img: '87' },
  { id: '89', ja: '明日は雨が降ると思いますか？', en: 'Do you think it will rain tomorrow?', img: '88' },
  { id: '90', ja: '兄弟はいますか？', en: 'Do you have any siblings?', img: '89' },
  { id: '91', ja: '旅行が好きですか', en: 'Do you like to travel?', img: '90' },
  { id: '92', ja: '疲れています', en: "I'm tired", img: '91' },
  { id: '93', ja: 'お腹が空いていません', en: "I'm not hungry", img: '92' },
  { id: '94', ja: '今、忙しいです', en: "I'm busy right now", img: '93' },
  { id: '95', ja: '冗談を聞く気分ではありません', en: "I'm not in the mood for jokes", img: '94' },
  { id: '96', ja: '手伝えて嬉しいです', en: "I'm happy to help", img: '95' },
  { id: '97', ja: 'よくわかりません', en: "I'm not sure", img: '96' },
  { id: '98', ja: '寒いです', en: "I'm cold", img: '97' },
  { id: '99', ja: '朝型ではありません', en: "I'm not a morning person", img: '98' },
  { id: '100', ja: '新しいプロジェクトを始めるのが楽しみです', en: "I'm excited to start a new project", img: '99' },
  { id: '101', ja: '体調が悪いです', en: "I'm not feeling well", img: '100' },
  { id: '102', ja: 'あなたの手伝いに感謝しています', en: "I'm grateful for your help", img: '101' },
  { id: '103', ja: '興味がありません', en: "I'm not interested", img: '102' },
  { id: '104', ja: '土曜日は都合がいいです', en: "I'm available on Saturday", img: '103' },
  { id: '108', ja: '急いでいる', en: "I'm in a rush", img: '104' },
  { id: '112', ja: 'ごめんなさい', en: "I'm sorry", img: '108' },
  { id: '115', ja: '退屈だ', en: "I'm bored", img: '109' },
  { id: '117', ja: '都合がつかない', en: "I'm not available", img: '110' },
  { id: '118', ja: 'ワクワクしている', en: "I'm excited", img: '111' },
  { id: '119', ja: 'これが苦手だ', en: "I'm not good at this", img: '112' },
  { id: '120', ja: '遅れている', en: "I'm late", img: '113' },
  { id: '121', ja: 'それには違和感がある', en: "I'm not comfortable with that", img: '114' },
  { id: '122', ja: 'それを聞いて残念です', en: "I'm sorry to hear that", img: '115' },
  { id: '123', ja: 'あなたの申し出には興味がありません', en: "I'm not interested in your offer", img: '116' },
  { id: '124', ja: 'あなたのことを幸せに思います', en: "I'm happy for you", img: '117' },
  { id: '125', ja: '何をすればいいのかわからない', en: "I'm not sure what to do", img: '118' },
  { id: '126', ja: '準備はいいですか？', en: "Are you ready?", img: '119' },
  { id: '127', ja: '忙しいですか？', en: "Are you busy?", img: '120' },
  { id: '128', ja: '一緒に来るんですか？', en: "Are you coming with us?", img: '121' },
  { id: '129', ja: 'それで本当にいいんですか？', en: "Are you sure about that?", img: '122' },
  { id: '130', ja: '元気になりましたか？', en: "Are you feeling better?", img: '123' },
  { id: '132', ja: '起こったことに本当に申し訳ありません', en: "I'm really sorry about what happened", img: '124' },
  { id: '133', ja: '今夜は外出する気分ではありません', en: "I'm not in the mood to go out tonight", img: '125' },
  { id: '134', ja: '私はベジタリアンです', en: "I'm a vegetarian", img: '126' },
  { id: '135', ja: 'あなたのパーティーに参加できるかどうかわかりません', en: "I'm not sure if I can come to your party", img: '127' },
  { id: '136', ja: '出会えて本当によかったです', en: "I'm so glad we met", img: '128' },
  { id: '138', ja: '本当にお腹が空いています', en: "I'm really hungry", img: '129' },
  { id: '139', ja: '数学はあまり得意ではありません', en: "I'm not very good at math", img: '130' },
  { id: '140', ja: '申し訳ありませんが、それには手伝えません', en: "I'm sorry, I can't help you with that", img: '131' },
  { id: '141', ja: 'ピーナッツアレルギーです', en: "I'm allergic to peanuts", img: '132' },
  { id: '142', ja: 'この状況には不快感を覚えます', en: "I'm not comfortable with this situation", img: '133' },
  { id: '143', ja: '現在は恋愛には興味がありません', en: "I'm not interested in dating right now", img: '134' },
  { id: '144', ja: '本当に疲れています', en: "I'm really tired", img: '135' },
  { id: '146', ja: '今夜のパーティーが楽しみでたまりません', en: "I'm really excited for the party tonight", img: '136' },
  { id: '147', ja: 'あなたが言いたいことが理解できない', en: "I'm not sure I understand what you mean", img: '137' },
  { id: '148', ja: 'あなたが元気であることを聞いてうれしいです', en: "I'm happy to hear that you're doing well", img: '138' },
  { id: '149', ja: 'このような気候に慣れていません', en: "I'm not used to this kind of weather", img: '139' },
  { id: '150', ja: '大丈夫ですか？', en: "Are you feeling okay?", img: '140' },
  { id: '151', ja: '今忙しいですか？', en: "Are you busy right now?", img: '141' },
  { id: '152', ja: '今夜のパーティーに来ますか？', en: "Are you coming to the party tonight?", img: '142' },
  { id: '154', ja: '寿司が好きですか？', en: "Are you a fan of sushi?", img: '143' },
  { id: '155', ja: '来週会う予定はありますか', en: "Are you available to meet next week?", img: '144' },
  { id: '158', ja: '大丈夫ですか？', en: "Are you okay?", img: '145' },
  { id: '160', ja: '彼は上手な歌手です', en: "He's a good singer", img: '146' },
  { id: '161', ja: '彼女は気分がすぐれません', en: "She's not feeling well", img: '147' },
  { id: '162', ja: '私たちは公園に行きます', en: "We're going to the park", img: '148' },
  { id: '163', ja: '自信がありません', en: "We're not sure", img: '149' },
  { id: '164', ja: '彼らは私の友達です', en: "They're my friends", img: '150' },
  { id: '165', ja: '彼らは政治に興味がありません', en: "They're not interested in politics", img: '151' },
  { id: '168', ja: 'これは私の本です', en: "This is my book", img: '152' },
  { id: '169', ja: '注文したものと違います', en: "This is not what I ordered", img: '153' },
  { id: '170', ja: 'それは素晴らしいアイデアです', en: "That's a great idea", img: '154' },
  { id: '171', ja: '不公平です', en: "That's not fair", img: '155' },
  { id: '172', ja: '幸せです', en: "I'm happy", img: '156' },
  { id: '175', ja: 'パーティーに来ますか？', en: "Are you coming to the party?", img: '157' },
  { id: '176', ja: '彼は背が高いです', en: "He's tall", img: '158' },
  { id: '178', ja: '道に迷いました', en: "We're lost", img: '159' },
  { id: '179', ja: '間に合いません', en: "We're not going to make it", img: '160' },
  { id: '180', ja: '彼らはもうすぐ出発します', en: "They're leaving soon", img: '161' },
  { id: '181', ja: '彼らは来ません', en: "They're not coming", img: '162' },
  { id: '182', ja: '雨が降っています', en: "It's raining", img: '163' },
  { id: '183', ja: 'うまくいっていません', en: "It's not working", img: '164' },
  { id: '184', ja: 'これは私の車です', en: "This is my car", img: '165' },
  { id: '185', ja: '期待していたものと違います', en: "This is not what I expected", img: '166' },
  { id: '186', ja: 'それは高価です', en: "That's expensive", img: '167' },
  { id: '187', ja: 'それは本当ではありません', en: "That's not true", img: '168' },
  { id: '191', ja: '日本から来ましたか？', en: "Are you from Japan?", img: '169' },
  { id: '192', ja: '彼は私の兄です', en: "He's my brother", img: '170' },
  { id: '193', ja: '彼女は幸せではありません', en: "She's not happy", img: '171' },
  { id: '194', ja: '遅刻しています', en: "We're late", img: '172' },
  { id: '195', ja: '道に迷っていません', en: "We're not lost", img: '173' },
  { id: '197', ja: 'まだここにいません', en: "They're not here yet", img: '174' },
  { id: '198', ja: '今日は暑いです', en: "It's hot today", img: '175' },
  { id: '199', ja: '私の責任ではありません', en: "It's not my fault", img: '176' },
  { id: '200', ja: 'これはあなたの部屋です', en: "This is your room", img: '177' },
  { id: '201', ja: '欲しかったものと違います', en: "This is not what I wanted", img: '178' },
  { id: '202', ja: 'とてもおいしいです', en: "That's delicious", img: '179' },
  { id: '203', ja: '必要ありません', en: "That's not necessary", img: '180' },
  { id: '204', ja: '急いでいます', en: "I'm in a hurry", img: '181' },
  { id: '206', ja: '初めてですか？', en: "Are you new here?", img: '182' },
  { id: '207', ja: '大丈夫ですか？', en: "Are you feeling okay?", img: '183' },
  { id: '208', ja: '彼は医者です', en: "He's a doctor", img: '184' },
  { id: '209', ja: '彼女はまだ準備ができていません', en: "She's not ready yet", img: '185' },
  { id: '210', ja: '楽しんでいます', en: "We're having fun", img: '186' },
  { id: '211', ja: 'まだ終わっていません', en: "We're not finished yet", img: '187' },
  { id: '212', ja: '彼らは親友です', en: "They're good friends", img: '188' },
  { id: '213', ja: '彼らは帰ってきません', en: "They're not coming back", img: '189' },
  { id: '215', ja: '大したことではありません', en: "It's not a big deal", img: '190' },
  { id: '216', ja: 'これは間違いです', en: "This is a mistake", img: '191' },
  { id: '217', ja: 'こちらは正しい道ではありません', en: "This is not the right way", img: '192' },
  { id: '218', ja: 'そのドレス素敵ですね', en: "That's a nice dress", img: '193' },
  { id: '219', ja: '私の問題ではありません', en: "That's not my problem", img: '194' },
  { id: '220', ja: '遅れています', en: "I'm running late", img: '195' },
  { id: '222', ja: 'お腹すいていますか？', en: "Are you hungry?", img: '196' },
  { id: '223', ja: '今夜は予定がありますか？', en: "Are you available tonight?", img: '197' },
  { id: '224', ja: '彼は芸術家です', en: "He's an artist", img: '198' },
  { id: '225', ja: '彼女は今ここにいません', en: "She's not here right now", img: '199' },
  { id: '226', ja: '同じチームです', en: "We're on the same team", img: '200' },
  { id: '227', ja: 'まだ確信がありません', en: "We're not sure yet", img: '201' },
  { id: '228', ja: '後で来ます', en: "They're coming over later", img: '202' },
  { id: '229', ja: 'それには興味がありません', en: "They're not interested in that", img: '203' },
  { id: '230', ja: '外は雨が降っています', en: "It's raining outside", img: '204' },
  { id: '231', ja: '予想したものと違います', en: "It's not what I expected", img: '205' },
  { id: '232', ja: 'すごいです', en: "This is amazing", img: '206' },
  { id: '233', ja: '公平ではありません', en: "This is not fair", img: '207' },
  { id: '234', ja: 'いい考えですね', en: "That's a good idea", img: '208' },
  { id: '235', ja: '問題ありません', en: "That's not a problem", img: '209' },
  { id: '236', ja: '週末を楽しみにしています', en: "I'm looking forward to the weekend", img: '210' },
  { id: '238', ja: '行く準備はできていますか？', en: "Are you ready to go?", img: '212' },
  { id: '239', ja: 'パーティーに行く予定ですか？', en: "Are you going to the party?", img: '213' },
  { id: '240', ja: '彼は今は手が空いていません', en: "He's not available right now", img: '214' },
  { id: '241', ja: '彼女は私の親友です', en: "She's my best friend", img: '215' },
  { id: '242', ja: '時間がなくなってきています', en: "We're running out of time", img: '216' },
  { id: '243', ja: 'それをすることは許されていません', en: "We're not allowed to do that", img: '217' },
  { id: '244', ja: '彼らは来週の休みに出かけます', en: "They're going on vacation next week", img: '218' },
  { id: '245', ja: '彼らは会議に来ません', en: "They're not coming to the meeting", img: '219' },
  { id: '246', ja: '外が暗くなってきています', en: "It's getting dark outside", img: '220' },
  { id: '247', ja: '大したことではありません', en: "It's not a big deal", img: '221' },
  { id: '248', ja: 'これは私のお気に入りの曲です', en: "This is my favorite song", img: '222' },
  { id: '250', ja: 'そのドレスはとても美しいです', en: "That's a beautiful dress", img: '223' },
  { id: '251', ja: 'そんなつもりじゃない', en: "That's not what I meant", img: '224' },
  { id: '253', ja: '理解できているか、自信がない', en: "I'm not sure I understand", img: '225' },
  { id: '255', ja: '仕事に行くつもりですか？', en: "Are you going to the work?", img: '226' },
  { id: '256', ja: '彼はいつも遅れます', en: "He's always late", img: '227' },
  { id: '257', ja: '彼女は今日体調が良くありません', en: "She's not feeling well today", img: '228' },
  { id: '258', ja: 'もうすぐ着きます', en: "We're almost there", img: '229' },
  { id: '259', ja: 'ここに居たらマズイ', en: "We're not supposed to be here", img: '230' },
  { id: '260', ja: '彼らはサプライズパーティーを計画しています', en: "They're planning a surprise party", img: '231' },
  { id: '261', ja: '彼らは行けるかどうかわかりません', en: "They're not sure if they can make it", img: '232' },
  { id: '272', ja: '外は寒すぎます', en: "It's too cold outside", img: '233' },
  { id: '274', ja: 'これは私が今まで食べた中で最高のピザです', en: "This is the best pizza I've ever had", img: '234' },
  { id: '276', ja: 'それは素晴らしいアイデアです！', en: "That's a great idea!", img: '235' },
  { id: '278', ja: 'これを手伝ってくれますか？', en: "Do you help me with this?", img: '236' },
  { id: '279', ja: '他の言語を話せますか？', en: "Do you speak any other languages?", img: '237' },
  { id: '280', ja: '遅れてごめんなさい', en: "I'm sorry I'm late", img: '238' },
  { id: '281', ja: '何を着るべきかわかりません', en: "I'm not sure what to wear", img: '239' },
  { id: '282', ja: '一緒にコンサートに来てくれますか？', en: "Are you coming to the concert with me?", img: '240' },
  { id: '283', ja: '芸術に興味がありますか？', en: "Are you interested in art?", img: '241' },
  { id: '284', ja: '彼はギターを弾くのが本当に上手です', en: "He's really good at playing the guitar", img: '242' },
  { id: '286', ja: 'ロードトリップに行く予定です', en: "We're going on a road trip", img: '243' },
  { id: '294', ja: '私は喉が渇きました', en: "I'm thirsty", img: '244' },
  { id: '295', ja: '私は病気です', en: "I'm sick", img: '245' },
  { id: '297', ja: '私は暑いです', en: "I'm hot", img: '246' },
  { id: '300', ja: '私は緊張しています', en: "I'm nervous", img: '247' },
  { id: '301', ja: 'あなたに会えて嬉しいです', en: "I'm happy to meet you", img: '248' },
  { id: '306', ja: '私はまだ準備ができていません', en: "I'm not ready yet", img: '249' },
  { id: '307', ja: '私はそれについて納得していない', en: "I'm not happy about this", img: '250' },
  { id: '309', ja: '私はこの辺り出身ではありません', en: "I'm not from around here", img: '251' },
  { id: '313', ja: '来ますか？', en: "Are you coming?", img: '252' },
  { id: '314', ja: '確信がありますか？', en: "Are you sure?", img: '253' },
  { id: '316', ja: '喉が渇いていますか？', en: "Are you thirsty?", img: '254' },
  { id: '317', ja: '終わりましたか？', en: "Are you done?", img: '255' },
  { id: '318', ja: '冗談ですか？', en: "Are you joking?", img: '256' },
  { id: '319', ja: '結婚されていますか？', en: "Are you married?", img: '257' },
  { id: '320', ja: '本気ですか？', en: "Are you serious?", img: '258' },
  { id: '321', ja: '英語を話せますか？', en: "Do you speak English?", img: '259' },
  { id: '322', ja: '質問がありますか？', en: "Do you have a question?", img: '260' },
  { id: '323', ja: '私と一緒に行きたいですか？', en: "Do you want to come with me?", img: '261' },
  { id: '324', ja: '助けが必要ですか？', en: "Do you need help?", img: '262' },
  { id: '325', ja: '理解していますか？', en: "Do you understand?", img: '263' },
  { id: '326', ja: 'コーヒーが好きですか？', en: "Do you like coffee?", img: '264' },
  { id: '327', ja: '兄弟姉妹はいますか？', en: "Do you have any siblings?", img: '265' },
  { id: '328', ja: 'ペットは飼っていますか？', en: "Do you have any pets?", img: '266' },
  { id: '338', ja: '私は混乱しています', en: "I'm confused", img: '267' },
  { id: '339', ja: '私は仕事に満足しています', en: "I'm happy with my job", img: '268' },
  { id: '344', ja: '私は準備ができていません', en: "I'm not ready", img: '269' },
  { id: '351', ja: '私の話を聞いていますか？', en: "Are you listening to me?", img: '270' },
  { id: '353', ja: 'この辺り出身ですか？', en: "Are you from around here?", img: '271' },
  { id: '354', ja: '学生ですか？', en: "Are you a student?", img: '272' },
  { id: '355', ja: '私はそれに興味がありません', en: "I'm not interested in that", img: '273' },
  { id: '356', ja: '私はそれについて確信がない', en: "I'm not sure about it", img: '274' },
  { id: '357', ja: '私はあまりお腹が空いていません', en: "I'm not that hungry", img: '275' },
  { id: '358', ja: '私はその気分ではありません', en: "I'm not in the mood", img: '276' },
  { id: '360', ja: '私はこの天気に慣れていません', en: "I'm not used to this weather", img: '277' },
]
